"""Legacy import path. Policy text is generated by AIService.generate_policy_law."""

async def generate_policy_law(
    category: str,
    nation_name: str,
    issue_title: str,
    issue_description: str,
    choice_text: str,
    stat_effects: dict = None,
    government: str = "",
    choice_description: str = "",
):
    from ai_service import AIService

    svc = AIService()
    return await svc.generate_policy_law(
        category=category,
        nation_name=nation_name,
        government=government or "",
        issue_title=issue_title,
        issue_description=issue_description,
        choice_text=choice_text,
        choice_description=choice_description or "",
    )
