import { HUMAN, put } from './govOperating.store';

const Y = 'federacy / asymmetrical federation';
const I = 'imperial / hegemonic';
const CS = 'Constitutional / Limited';
const POP = 'Populist';
const MIL = 'Military-Influenced';
const PAT = 'Paternalist / Welfare-First';
const TRAD = 'Traditional / Hereditary';
const THEO = 'Theocratic Influence';
const TECH = 'Technocratic';
const REV = 'Revolutionary / Provisional';
const CORP = 'Corporate / Business Elite';
const BUR = 'Bureaucratic';
const ECO = 'Ecological / Green-Influenced';
const MER = 'Meritocratic';
const CHA = 'Charismatic Leader Focus';
const PRAE = 'Praetorian / Security-State';
const LIB = 'Libertarian / Minimal-State';
const PART = 'Participatory / Deliberative';
const ISO = 'Isolationist';

function s(sub: string, terr: string, style: string, text: string) {
  put(HUMAN, sub, terr, style, text);
}

export function loadDemocracyAsymStacks() {
  const RD = 'Representative Democracy';
  const Parl = 'Parliamentary Democracy';
  const Pres = 'Presidential Democracy';
  const DR = 'Democratic Republic';
  const Dir = 'Direct Democracy';
  const Con = 'Consociational Democracy';
  const Del = 'Deliberative Democracy';

  s(RD, Y, CS, 'The union house is elected under a charter, except the special regions whose side letters sit above that charter. Equality before the constitution is a slogan the exceptions can quote.');
  s(RD, Y, POP, 'The crowd in the ordinary states can sweep the union and still bounce off a privileged region that never needed the crowd.');
  s(RD, Y, MIL, 'Most states share a staff. The special region kept its own command in the side deal. Deputies who forget that start a war by memo.');
  s(RD, Y, PAT, 'Union stipends stop at the special border, or only exist there. Citizens learn which map pays.');
  s(RD, Y, TRAD, 'The exception is usually an old house. Ordinary states elect; that region remembers.');
  s(RD, Y, THEO, 'A holy exception keeps family law the union house cannot touch. The charter has a hole shaped like a sanctuary.');
  s(RD, Y, TECH, 'Union institutes plan around a region that runs its own numbers. The five-year table has a blank province.');
  s(RD, Y, REV, 'The capital still talks like a founding. The privileged region never joined that mood and treats emergency acts as someone else’s rupture.');
  s(RD, Y, CORP, 'Firms incorporate in the exception. The union house regulates everyone else.');
  s(RD, Y, BUR, 'Two kinds of circulars: ordinary and exempt. Citizens at the line carry both and still get the wrong stamp.');
  s(RD, Y, ECO, 'A special region can freeze a river the union ballot opened, by treaty rather than by vote.');
  s(RD, Y, MER, 'Union offices exam ordinary applicants. The exception hires by name and still sits in the same chamber.');
  s(RD, Y, CHA, 'A union face stops at the privileged border. That region has its own names and does not need the banners.');
  s(RD, Y, LIB, 'The union stays thin; the exception stays thinner or thicker by deal. “Minimal state” is not evenly distributed.');
  s(RD, Y, PART, 'Town votes bind ordinary deputies. The special region’s people may not even be on that floor.');
  s(RD, Y, ISO, 'The union would rather not go abroad. The exception may already have a foreign cousin written into its side letter.');
  s(RD, Y, PRAE, 'Union guards do not enter the exception without a phone call. That phone call is the real constitution.');

  s(Parl, Y, CS, 'The union cabinet lives on confidence, except where a region’s veto on money bills is older than the house. A majority can still starve in a hole in the charter.');
  s(Parl, Y, POP, 'Premiers campaign the ordinary map. The privileged region does not attend rallies it cannot be whipped by.');
  s(Parl, Y, MIL, 'Union defence estimates skip a command that the side deal left standing. Officers there do not fall with the premier.');
  s(Parl, Y, PAT, 'The union dole is a coalition glue except in the region that kept its own purse. Premiers who centralize it start a secession rumor.');
  s(Parl, Y, TRAD, 'The exception is a leftover estate. Modern parties work around a bench they cannot fill.');
  s(Parl, Y, THEO, 'A godly exception can deny supply without sitting in the union house. Faith is a side letter.');
  s(Parl, Y, TECH, 'Planning boards draw around a blank. The region’s own institute does not send the table.');
  s(Parl, Y, REV, 'Enabling acts bind the ordinary states. The privileged region files them under “not our uprising.”');
  s(Parl, Y, CORP, 'Combines keep the exception as a legal island. Cabinets that surprise the island find their majority suddenly “concerned.”');
  s(Parl, Y, BUR, 'Union circulars and exemption circulars. A premier initials both and still cannot say which applied.');
  s(Parl, Y, ECO, 'The exception can keep a forest the union house sold. Green law is a privilege, not a principle.');
  s(Parl, Y, MER, 'Frontbench jobs want the file. The exception sends whoever the deal names, competent or not.');
  s(Parl, Y, CHA, 'The union following stops at the special border. That region was never in the following.');
  s(Parl, Y, LIB, 'Thin ministries, except the exception may run a thicker household by right. Minimal is for the others.');
  s(Parl, Y, PART, 'Local assemblies bind ordinary MPs. The privileged region’s voters may be instructed by a house that is not that assembly.');
  s(Parl, Y, ISO, 'Union entanglement dies in committee — unless the exception’s side letter already is an entanglement.');
  s(Parl, Y, PRAE, 'Union guards and the exception’s household troops do not share a key. Confidence in the capital is not a key.');

  s(Pres, Y, CS, 'The president is elected nationwide, except where a region bargained out of that story. Impeachment and courts stop at a door the charter itself opened.');
  s(Pres, Y, POP, 'The palace is a crowd. The exception is not in the crowd and does not need to be.');
  s(Pres, Y, MIL, 'Commander-in-chief, except of the force the side deal left local. The palace learns this during the first emergency.');
  s(Pres, Y, PAT, 'Presidential clinics skip, or only exist in, the privileged map. Disaster money has a footnote.');
  s(Pres, Y, TRAD, 'The exception is usually a leftover court. The president swears a republican oath and then writes to a prince.');
  s(Pres, Y, THEO, 'A holy exception freezes decrees the palace thought were national. The oath did not mention that sanctuary.');
  s(Pres, Y, TECH, 'Union experts plan around a province that will not share data. The dashboard has a polite hole.');
  s(Pres, Y, REV, 'Emergency clauses bind the ordinary republic. The exception files them as foreign paper.');
  s(Pres, Y, CORP, 'The island of privilege is where the combines actually live. The palace regulates the rest.');
  s(Pres, Y, BUR, 'A decree needs the extra stamp. Presidents discover the extra stamp after the ceremony.');
  s(Pres, Y, ECO, 'The exception’s land court can halt a presidential project the rest of the union already funded.');
  s(Pres, Y, MER, 'Union secretaries are professionals. The exception’s officers are named in a letter older than the exam.');
  s(Pres, Y, CHA, 'The face on the banners is unknown in the privileged region, which has its own portraits.');
  s(Pres, Y, LIB, 'The palace stays small; the exception may be a miniature state of its own. Thinness is uneven.');
  s(Pres, Y, PART, 'Town votes bind ordinary states. The exception’s people may vote in a different ritual, or not on that file at all.');
  s(Pres, Y, ISO, 'The palace sells staying home. The exception’s side letter may already be a foreign marriage.');
  s(Pres, Y, PRAE, 'Union interior troops knock. The exception’s household opens, or does not. That knock is the federacy.');

  s(DR, Y, CS, 'The flag is republican, with a footnote region that is not a peer. Entrenchment protects the footnote as much as the rights.');
  s(DR, Y, POP, 'The republic performs the people — except the people who live under the side letter, who perform someone else.');
  s(DR, Y, MIL, 'The republic’s force stops at a garrison the deal left standing. Guardianship is local there.');
  s(DR, Y, PAT, 'Civic packages skip the exception, or exist only there. Equality of benefits is a brochure.');
  s(DR, Y, TRAD, 'A princely leftover inside a republic. Civic holidays stop at that gate.');
  s(DR, Y, THEO, 'The civic creed is union-wide until a holy exception says otherwise.');
  s(DR, Y, TECH, 'Union colleges do not staff the footnote. It keeps its own savants and its own standards.');
  s(DR, Y, REV, 'The overthrow’s calendar is not observed in the region that never overthrew.');
  s(DR, Y, CORP, 'The exception is a charter island. Republican virtue is taught next door.');
  s(DR, Y, BUR, 'Two passports of paperwork. The footnote’s forms outrank the republic’s at the line.');
  s(DR, Y, ECO, 'A leftover court can keep a forest the republican majority sold.');
  s(DR, Y, MER, 'Magistrates exam in the republic. The exception’s seats are named.');
  s(DR, Y, CHA, 'The republic’s face does not hang in the footnote, which never voted for a face.');
  s(DR, Y, LIB, 'The republic stays small; the exception may be a denser little state. The slogan does not travel.');
  s(DR, Y, PART, 'Citizenship-as-job stops at the special border, or is only real there.');
  s(DR, Y, ISO, 'The republic does not hunt monsters. The footnote may already be someone else’s cousin.');
  s(DR, Y, PRAE, 'Republican guards and household troops share a flag and not a password.');

  s(Dir, Y, CS, 'Most citizens ballot on what binds them. The special territories’ side deals keep some files off the floor by entrenched right.');
  s(Dir, Y, POP, 'The ordinary map is a permanent campaign. The exception does not need one; it already won in the footnote.');
  s(Dir, Y, MIL, 'The assembly votes war except where a leftover command does not ask.');
  s(Dir, Y, PAT, 'The floor votes stipends that may not enter the privileged region, or may only exist there.');
  s(Dir, Y, THEO, 'Sacred files are off the union ballot in the holy exception. Direct democracy has a sanctuary-shaped silence.');
  s(Dir, Y, TECH, 'Options on the paper were written without the exception’s institute. That region votes a different paper, or none.');
  s(Dir, Y, REV, 'Emergency votes bind the square. The footnote never stood in that square.');
  s(Dir, Y, CORP, 'Signature money floods the ordinary floor. The exception is already owned, cheaper.');
  s(Dir, Y, BUR, 'A popular yes waits on exemption rules. The people voted; the footnote did not have to.');
  s(Dir, Y, ECO, 'The exception can keep a river the union ballot opened, by deal rather than by turnout.');
  s(Dir, Y, MER, 'Drafting boards exam ordinary proposers. The exception’s text arrives by name.');
  s(Dir, Y, CHA, 'A union voice swings the ordinary floor and dies at a region that never liked the voice.');
  s(Dir, Y, LIB, 'Ordinary ballots love nos. The exception may be a thicker little regime by right.');
  s(Dir, Y, PART, 'Juries and sortition in the ordinary map. The footnote may use a different ritual entirely.');
  s(Dir, Y, ISO, 'Union pacts die on the floor — unless the exception’s letter already is a pact.');
  s(Dir, Y, PRAE, 'Union guards run ordinary ballots. The exception’s household runs theirs, or cancels them.');

  s(Con, Y, CS, 'Power-sharing is the rule, plus one region with a thicker shield. That shield is as constitutional as the quotas.');
  s(Con, Y, POP, 'Communal tribunes stop at the privileged door. That community already has a better deal than a crowd.');
  s(Con, Y, MIL, 'The mixed army is mixed except in the region that kept its own. Officers there are a veto the seating plan cannot see.');
  s(Con, Y, PAT, 'Communal welfare, plus a region whose list is sealed. Mixing that list is a treaty breach.');
  s(Con, Y, TRAD, 'The thicker shield is usually an old house. Quotas meet a leftover crown.');
  s(Con, Y, THEO, 'Personal status law is already plural. The exception’s rite is more so, by paper.');
  s(Con, Y, TECH, 'Shared boards plan around a community that will not pool data. The table has a polite hole.');
  s(Con, Y, REV, 'The settlement is a truce. The privileged region never needed that truce and treats emergency as someone else’s war.');
  s(Con, Y, CORP, 'The exception is a combine’s reservation. Other communities strike; that one invoices.');
  s(Con, Y, BUR, 'Duplicate offices, plus a third stack for the footnote. Peace is thicker paper.');
  s(Con, Y, ECO, 'A privileged water can be fenced off from the shared green law.');
  s(Con, Y, MER, 'Communal exams, except the exception’s nominees are named. Competence is a quota with a hole.');
  s(Con, Y, LIB, 'The center stays weak so no bloc can use it — except the bloc that already used the side letter.');
  s(Con, Y, PART, 'Communal halls bind slates. The privileged region’s hall may not even send one.');
  s(Con, Y, ISO, 'Foreign patrons are forbidden unless every bloc signs — except the exception’s patron, already in the letter.');
  s(Con, Y, PRAE, 'Inner troops are communal, plus a household in the footnote that does not mix.');

  s(Del, Y, CS, 'Process is entrenched, except the special region whose charter lets it skip forums on the files it cares about.');
  s(Del, Y, POP, 'Authentic voice is chased everywhere but the footnote, which already has a quieter deal.');
  s(Del, Y, MIL, 'Officers sit in hearings, except the leftover command that does not attend and still vetoes.');
  s(Del, Y, PAT, 'Hearings end in stipends that may not cross the privileged line.');
  s(Del, Y, TRAD, 'Speaking order is old; the exception’s order is older and not on the union agenda.');
  s(Del, Y, THEO, 'Public reason includes scripture, except where the footnote’s scripture outranks the hearing.');
  s(Del, Y, TECH, 'Briefing books skip a region that will not be briefed. Consensus has a hole.');
  s(Del, Y, REV, 'The founding assembly never closed. The privileged region never opened it.');
  s(Del, Y, CORP, 'Stakeholder tables, plus a region that is already a stakeholder by treaty.');
  s(Del, Y, BUR, 'Comment periods, plus an exemption from comment. Process is for the others.');
  s(Del, Y, ECO, 'Advocates for the land, except the footnote’s land is already fenced in the side letter.');
  s(Del, Y, MER, 'Sortition and training, except the exception’s seats are not drawn.');
  s(Del, Y, CHA, 'The union magnet does not work in a region that opted out of the circle.');
  s(Del, Y, LIB, 'Deliberation brakes the union. The exception may already be a denser little state.');
  s(Del, Y, PART, 'Paid attendance in ordinary regions. The footnote may not owe that duty.');
  s(Del, Y, ISO, 'Treaties die in hearings — unless the exception’s letter already is a treaty.');
  s(Del, Y, PRAE, 'Inner troops sit in ordinary hearings. The exception’s household does not share the room.');

  // Imperial × style (3A: metro voters, subject marches) — skip Isolationist as straggler
  s(RD, I, CS, 'The core’s charter binds the house. It does not bind the marches, which live under governors and enabling clauses the constitution calls “overseas.”');
  s(RD, I, POP, 'The metropolitan crowd elects a chamber that argues about people who cannot vote. Tribunes sell the empire as the people’s estate.');
  s(RD, I, MIL, 'The house votes estimates; the staff already occupies. Subject garrisons are not a civilian file.');
  s(RD, I, PAT, 'Citizens at the core get clinics. Subject towns get ration and a flag. Kindness is a citizenship test.');
  s(RD, I, TRAD, 'The core’s old families staff the colonial office. Subject notables are clients, not cousins.');
  s(RD, I, THEO, 'The metropole’s pulpit blesses the mission. Outer creeds are folklore until they rebel.');
  s(RD, I, TECH, 'Institutes in the capital plan other people’s rivers. The marches send data, not deputies.');
  s(RD, I, REV, 'The core’s founding is a holiday. The marches’ founding is an occupation date.');
  s(RD, I, CORP, 'Chartered companies are how the house outsources the empire. Profit is metropolitan; risk is provincial.');
  s(RD, I, BUR, 'Two codes: civic paper at home, pass laws abroad. Rights wait in different queues.');
  s(RD, I, ECO, 'The core votes parks. The marches get the mines that pay for the parks.');
  s(RD, I, MER, 'Exams for the colonial service. Subject talent staffs, it does not sit.');
  s(RD, I, CHA, 'The metropolitan face is printed on provincial offices. The provinces did not pick the face.');
  s(RD, I, LIB, 'Thin state at home, thick state in the marches. Liberty is a metropolitan export that does not ship.');
  s(RD, I, PART, 'Town votes in the core. Subject towns get notified.');
  s(RD, I, PRAE, 'Interior troops at home; occupation troops abroad. Different uniforms, same palace.');

  s(Parl, I, CS, 'A metropolitan parliament can fall a cabinet. It cannot fall a governor-general without a scene it calls “imperial affairs.”');
  s(Parl, I, POP, 'Premiers campaign the core. The empire is a cheer line, not a constituency.');
  s(Parl, I, MIL, 'Confidence topples cabinets; it does not topple occupying commands unless the house wants a war with its own staff.');
  s(Parl, I, PAT, 'The first budget is the metropolitan stipend. Provincial famine is an overseas estimate.');
  s(Parl, I, TRAD, 'The house is ancient; so is the colonial office. Subject kings, if any, sit as ornaments.');
  s(Parl, I, THEO, 'Godly benches bless the mission. Outer altars are regulated as security.');
  s(Parl, I, TECH, 'Plans for the empire are drawn where the votes are. Implementation is a staff problem on someone else’s map.');
  s(Parl, I, REV, 'Enabling acts at home; martial law abroad. Both claim the same founding.');
  s(Parl, I, CORP, 'Companies keep the majority interested in the marches. A cabinet that threatens a charter finds its backbench imperial.');
  s(Parl, I, BUR, 'Domestic circulars and colonial circulars. Subjects meet the second pile.');
  s(Parl, I, ECO, 'The house protects metropolitan rivers and auctions the others.');
  s(Parl, I, MER, 'Colonial service exams. Local talent translates, it does not question.');
  s(Parl, I, CHA, 'The premier’s face is the empire’s face. The marches did not follow; they were assigned.');
  s(Parl, I, LIB, 'Thin ministries at home. Thick prefects abroad. Minimal-state stops at the water.');
  s(Parl, I, PART, 'Local assemblies in the core. The empire is not a hearing.');
  s(Parl, I, PRAE, 'Guards of the capital and garrisons of the marches. Only one of those falls with the premier.');

  s(Pres, I, CS, 'The core’s president and congress check each other. Governors-general in the marches check no one the subjects elected.');
  s(Pres, I, POP, 'The palace is elected by the metropole and sold to the marches as destiny.');
  s(Pres, I, MIL, 'Commander-in-chief is real abroad. At home it is a title that still needs congress; in the provinces it does not.');
  s(Pres, I, PAT, 'Presidential clinics for voters. Rations for subjects. The motorcade only photographs the first.');
  s(Pres, I, TRAD, 'Court ritual at home; native courts as folklore abroad.');
  s(Pres, I, THEO, 'The metropolitan oath is scripture. Outer gods are a police file.');
  s(Pres, I, TECH, 'The palace’s experts plan other climates. The marches send samples.');
  s(Pres, I, REV, 'Emergency at home is a clause. Emergency abroad is the government.');
  s(Pres, I, CORP, 'Boardrooms pick the colonial cabinet. The elected palace picks the domestic one, sometimes.');
  s(Pres, I, BUR, 'Civic permits at home; movement orders abroad.');
  s(Pres, I, ECO, 'A metropolitan park; a provincial pit. Green is a citizenship perk.');
  s(Pres, I, MER, 'Examined secretaries for voters. Appointed residents for everyone else.');
  s(Pres, I, CHA, 'The face is elected in the core and printed on offices that never saw a ballot.');
  s(Pres, I, LIB, 'Vetoes keep the core small. The marches get agencies without vetoes.');
  s(Pres, I, PART, 'Town initiatives for citizens. Notifications for subjects.');
  s(Pres, I, PRAE, 'Palace guard at home; occupation at the edge. Different jobs, same loyalty test.');

  s(DR, I, CS, 'No crown at home. Plenty of occupying committees abroad. The charter’s silence on the marches is the point.');
  s(DR, I, POP, 'The republic is the people — the metropolitan people. Everyone else is a project.');
  s(DR, I, MIL, 'Civilian offices at home; the spare republic with medals runs the empire.');
  s(DR, I, PAT, 'Civic packages for citizens. Subject towns get a school named Virtue and a curfew.');
  s(DR, I, TRAD, 'Founding families staff the overseas file. Republican holidays are for the core.');
  s(DR, I, THEO, 'Civic creed at home; missions abroad. Blasphemy is a provincial crime.');
  s(DR, I, TECH, 'Colleges in the capital; field stations in the marches. Knowledge flows in; office does not flow out.');
  s(DR, I, REV, 'The overthrow liberated the core. The marches were “liberated” next, without being asked.');
  s(DR, I, CORP, 'National champions at home; concessions abroad. Virtue is a trademark.');
  s(DR, I, BUR, 'Rights queues for citizens; pass laws for subjects.');
  s(DR, I, ECO, 'Metropolitan commons; provincial extraction. The parks are paid in someone else’s trees.');
  s(DR, I, MER, 'Cursus honorum for citizens. Translators for the rest.');
  s(DR, I, CHA, 'The republic’s face is a metropolitan election printed on provincial walls.');
  s(DR, I, LIB, 'The republic cannot do much to its voters. It can do a great deal to its possessions.');
  s(DR, I, PART, 'Assemblies at home. The empire is a bulletin.');
  s(DR, I, PRAE, 'Republican guards for the capital; another corps for the map. Only one of them is photographed on civic day.');

  s(Dir, I, CS, 'The core ballots on everything, including other people’s lives, inside a charter that does not ask those people.');
  s(Dir, I, POP, 'The square votes the empire as a mood. Subject towns do not get a square.');
  s(Dir, I, MIL, 'The floor votes war; occupation already happened. The marches are a military fact with a popular stamp.');
  s(Dir, I, PAT, 'The floor votes itself stipends. Subject rations are an overseas motion nobody from there moved.');
  s(Dir, I, THEO, 'Sacred questions at home; forced rites or bans abroad, depending on the ballot’s temper.');
  s(Dir, I, TECH, 'Options framed in the capital. The marches are a dataset.');
  s(Dir, I, REV, 'Permanent assembly at home; permanent emergency abroad. Same founding, two calendars.');
  s(Dir, I, CORP, 'Initiatives about charters the combines already hold overseas.');
  s(Dir, I, BUR, 'A popular yes becomes a colonial circular. Subjects meet the circular.');
  s(Dir, I, ECO, 'The square saves a metropolitan river and opens a provincial one.');
  s(Dir, I, MER, 'The pen is expert at home. Abroad the pen is a resident’s.');
  s(Dir, I, CHA, 'The voice on the floor is the empire’s voice. The provinces hear it as an order.');
  s(Dir, I, LIB, 'The core votes to forbid powers over itself. It votes to keep them over the map.');
  s(Dir, I, PART, 'Juries for citizens. The empire is not a jury.');
  s(Dir, I, PRAE, 'Guards decide which ballots happen at home. In the marches the guard is the ballot.');

  s(Con, I, CS, 'Core communities share power by quota. Outer peoples are not a community in that deal; the charter calls them territories.');
  s(Con, I, POP, 'Each core street has a tribune. Subject streets have a prefect.');
  s(Con, I, MIL, 'Communal officers share the core army. Occupation of the marches is the one file they do not quota.');
  s(Con, I, PAT, 'Bloc welfare at home. Subject lists are a colonial office.');
  s(Con, I, TRAD, 'Old houses of the core staff the empire. Outer notables are clients.');
  s(Con, I, THEO, 'Holy courts for the core creeds. Outer rites are security.');
  s(Con, I, TECH, 'Mixed boards for core water. Provincial water is a plan target.');
  s(Con, I, REV, 'The core’s truce. The marches did not sign it and live under it anyway.');
  s(Con, I, CORP, 'Communal combines extract together abroad. Solidarity stops at citizenship.');
  s(Con, I, BUR, 'Duplicate offices at home; a single thick code abroad.');
  s(Con, I, ECO, 'Shared green law among the core. The marches pay in pits.');
  s(Con, I, MER, 'Exams for communal seats. Translators for the territories.');
  s(Con, I, LIB, 'The center stays weak so no core bloc can use it on the others. It is not weak in the marches.');
  s(Con, I, PART, 'Communal halls at home. Notifications abroad.');
  s(Con, I, PRAE, 'Inner troops are communal at home. Occupation troops are whoever drew the short quota.');

  s(Del, I, CS, 'The metropole talks for months. The marches live under last year’s conclusion, which the charter does not require them to have heard.');
  s(Del, I, POP, 'Authentic voice is metropolitan. Subject testimony is a briefing appendix.');
  s(Del, I, MIL, 'Officers sit in core hearings. In the marches they skip the hearing.');
  s(Del, I, PAT, 'Hearings end in stipends for citizens. Subjects get a program named after a virtue.');
  s(Del, I, TRAD, 'Old councils at home. Native councils as folklore abroad.');
  s(Del, I, THEO, 'Scripture as public reason in the core. Outer gods as a problem set.');
  s(Del, I, TECH, 'Briefing books about other climates, written where the forums are.');
  s(Del, I, REV, 'The founding debate never closed at home. Abroad it never opened.');
  s(Del, I, CORP, 'Firms sit in metropolitan stakeholder tables and hold the concessions the tables then bless.');
  s(Del, I, BUR, 'Comment periods for citizens. Movement orders for subjects.');
  s(Del, I, ECO, 'Advocates for metropolitan land. Provincial land is a line item.');
  s(Del, I, MER, 'Trained sortition at home. Appointed residents abroad.');
  s(Del, I, CHA, 'The magnet fills the metropolitan circle. The marches get the speech as a decree.');
  s(Del, I, LIB, 'The core uses talk to refuse powers over itself. It does not refuse them over the map.');
  s(Del, I, PART, 'Paid attendance at home. The empire is a bulletin.');
  s(Del, I, PRAE, 'Inner troops sit through metropolitan hearings. In the marches they are the process.');
}

loadDemocracyAsymStacks();
