import { NONE, UNITARY, HUMAN, put } from './govOperating.store';

const F = 'federal';
const C = 'confederal';
const Y = 'federacy / asymmetrical federation';
const I = 'imperial / hegemonic';
const CS = 'Constitutional / Limited';
const POP = 'Populist';
const MIL = 'Military-Influenced';
const PAT = 'Paternalist / Welfare-First';
const TRAD = 'Traditional / Hereditary';
const THEO = 'Theocratic Influence';
const TECH = 'Technocratic';
const REV = 'Revolutionary / Provisional';
const CORP = 'Corporate / Business Elite';
const BUR = 'Bureaucratic';
const ECO = 'Ecological / Green-Influenced';
const MER = 'Meritocratic';
const CHA = 'Charismatic Leader Focus';
const PRAE = 'Praetorian / Security-State';
const LIB = 'Libertarian / Minimal-State';
const PART = 'Participatory / Deliberative';
const ISO = 'Isolationist';

function s(sub: string, terr: string, style: string, text: string) {
  put(HUMAN, sub, terr, style, text);
}

export function loadDemocracyStacks() {
  const RD = 'Representative Democracy';
  const Parl = 'Parliamentary Democracy';
  const Pres = 'Presidential Democracy';
  const DR = 'Democratic Republic';
  const Dir = 'Direct Democracy';
  const Con = 'Consociational Democracy';
  const Del = 'Deliberative Democracy';

  // ——— FEDERAL × STYLE ———
  s(RD, F, CS, 'Voters fill a union house and statehouses, and a charter tells both what they may not touch. A federal statute that invades a state’s reserved file dies in court even if the national majority is huge.');
  s(RD, F, POP, 'National rallies talk like one people; the map votes like several. A tribune can sweep the union ballot and still bounce off statehouses that never liked the show.');
  s(RD, F, MIL, 'Each state keeps a militia culture; the union staff wants one army. Deputies who pick the garrison fight lose committee rooms they did not know were militarized.');
  s(RD, F, PAT, 'Union stipends and state stipends compete for loyalty. Citizens learn which layer actually pays the clinic, then vote that layer like a landlord.');
  s(RD, F, TRAD, 'Old families sit the state benches by habit and the union by courtesy. New parties can take the capital and still dine last in the provinces.');
  s(RD, F, THEO, 'A union majority cannot rewrite family law a holy statehouse has fenced. Pulpits are local; the federal file stops at the sanctuary door.');
  s(RD, F, TECH, 'Union planners draw the five-year rails; states keep the last mile. Campaigns argue morals, then both layers hand the numbers to institutes that do not share a boss.');
  s(RD, F, REV, 'The founding assembly never adjourned in the capital, and some states never joined the mood. Emergency acts bind the union; the holdout states treat them as foreign paper.');
  s(RD, F, CORP, 'Firms shop legislatures. A combine that loses the union house simply refiles the bill in a friendly state and waits for preemption to fail.');
  s(RD, F, BUR, 'Two stacks of circulars, two stamps. Elected ministers arrive to find the federal folders and the state folders already disagreeing.');
  s(RD, F, ECO, 'A state can freeze a river the union wants to dam. Green courts are local enough to ruin a national project and national enough to ruin a mill town.');
  s(RD, F, MER, 'Union offices want exams; some states still want cousins. The serious files migrate to whichever layer actually filters.');
  s(RD, F, CHA, 'The union campaign is a face. State machines are not; they outlast the face and quietly ignore it.');
  s(RD, F, LIB, 'The charter is used to keep both layers thin. New agencies die in the other house, which is the point of having two.');
  s(RD, F, PART, 'Town votes bind the state deputy; they do not automatically bind the union. Double mandates mean a popular local no can still lose in the capital.');
  s(RD, F, ISO, 'The union would rather not go abroad; some border states already live as if they did. Foreign policy is a federal monopoly that the frontier treats as optional.');
  s(RD, F, PRAE, 'Interior troops sit in the capital. Statehouses keep their own guards. A “national emergency” is whoever’s regiment arrived first.');

  s(Parl, F, CS, 'A union cabinet lives on confidence, but the charter and the statehouses can starve it without toppling it. Lose the court or the provinces and supply dies even if the whip still smiles.');
  s(Parl, F, POP, 'Premiers campaign as if the country were one crowd. Confidence still lives in a federal house that can be rural, quiet, and unimpressed.');
  s(Parl, F, MIL, 'Union defence is a confidence file the barracks already marked. State governments keep garrisons that do not fall when the premier does.');
  s(Parl, F, PAT, 'The first union budget is always the stipend; states run their own. A premier who centralizes the dole makes enemies of every provincial cabinet.');
  s(Parl, F, TRAD, 'Openings, estates, and inherited benches exist in both layers. A modern majority in the union house still rises when the old names enter a state chamber.');
  s(Parl, F, THEO, 'A godly statehouse can deny the union cabinet a quiet life. Faith benches do not need to sit in the capital to kill supply.');
  s(Parl, F, TECH, 'Question time is federal theatre. The plans are drawn in institutes that report to neither premier nor governor until someone initials the table.');
  s(Parl, F, REV, 'The union parliament still talks like a committee of the uprising. Some states never had that uprising and treat enabling acts as occupation law.');
  s(Parl, F, CORP, 'Combines keep a majority in one layer and a blocking minority in the other. Cabinets fall less often than bills are shopped.');
  s(Parl, F, BUR, 'Federal cabinets rotate; provincial directorates do not. A new premier inherits two civil services that have already met without them.');
  s(Parl, F, ECO, 'Green no-confidence can start in a statehouse over a union mine. The premier keeps the whip and loses the river.');
  s(Parl, F, MER, 'Frontbenches at both layers punish amateur ministers. A safe seat in a sleepy state will not survive a federal estimates hearing.');
  s(Parl, F, CHA, 'The union majority is a personal following. State premiers keep machines. When the face leaves, the provinces discover they were already governing.');
  s(Parl, F, LIB, 'Both houses treat new ministries as a reason to fall the government. Thinness is the coalition agreement across the map.');
  s(Parl, F, PART, 'Local assemblies bind their MPs; they do not bind the other states’ MPs. A cabinet can lose the street in three provinces and still sit until those benches flip.');
  s(Parl, F, ISO, 'Foreign adventures lose supply faster in the provinces than in the capital. Border states veto entanglement by starving the estimates.');
  s(Parl, F, PRAE, 'Union guards and state guards do not share a chain of command. A confidence vote the capital loves can still die at a provincial barrack gate.');

  s(Pres, F, CS, 'A union president, a union congress, and statehouses all swear the same charter. Gridlock is four-way: palace, congress, governors, and courts.');
  s(Pres, F, POP, 'The palace campaigns as the nation. Governors campaign as the real nation. Two popular mandates can point opposite ways until the term dies.');
  s(Pres, F, MIL, 'The commander-in-chief does not command state militias until a paper says so. Officers collect both phone numbers.');
  s(Pres, F, PAT, 'Disaster money is presidential; schools are often a governor’s. Loyalty follows the last check, not the constitution’s org chart.');
  s(Pres, F, TRAD, 'Statehouses keep ritual the palace cannot abolish. A reforming president wins the union and still has to bow in the provinces.');
  s(Pres, F, THEO, 'A holy governor can freeze a secular decree at the state line. The palace’s oath does not outrank that sanctuary.');
  s(Pres, F, TECH, 'Union institutes plan; state institutes implement or stall. The president chairs experts who do not control the last mile.');
  s(Pres, F, REV, 'The palace still dates itself from a rupture some states never signed. Emergency clauses bind the union; holdouts call them foreign.');
  s(Pres, F, CORP, 'Firms sue in the friendlier layer. A president who crosses the exchanges discovers a governor who did not.');
  s(Pres, F, BUR, 'Decrees wait on federal permits and state permits. The president can order a road that exists on one map and not the other.');
  s(Pres, F, ECO, 'A state land court can halt a presidential dam. Green vetoes are local, slow, and harder to fire than a secretary.');
  s(Pres, F, MER, 'Union ministries hire from exams; some states hire from county names. Competence pools in whichever layer pays the professionals.');
  s(Pres, F, CHA, 'The palace is a face. Governors are machines. The face leaves; the machines remain and start ignoring the vice office.');
  s(Pres, F, LIB, 'Both layers exist to veto the other. New agencies need two yeses and usually get none.');
  s(Pres, F, PART, 'Town initiatives bind governors more than presidents. A popular palace can still lose a state ballot the same week.');
  s(Pres, F, ISO, 'The palace sells staying home; a border governor already has cousins across the line. Foreign policy is federal on paper and local in practice.');
  s(Pres, F, PRAE, 'Union interior troops and state guards are rival electorates. A president who reforms the wrong regiment learns which building actually opens in the morning.');

  s(DR, F, CS, 'Two elective republics, stacked, both bound by a charter. A union majority cannot crown itself by eating a state’s reserved rights.');
  s(DR, F, POP, 'Each layer performs “the people.” The fight is which people: the union crowd or the state crowd.');
  s(DR, F, MIL, 'Civilian republics with two general staffs. Guardianship talk lives in whichever garrison is closer.');
  s(DR, F, PAT, 'Union citizenship is a benefit package; state citizenship is another. Losing either queue feels like exile.');
  s(DR, F, TRAD, 'Republican titles, inherited habits in the states. Founding families run provinces the capital pretends are civic.');
  s(DR, F, THEO, 'A civic union creed and local holy republics. Blasphemy against either is a federal-state incident.');
  s(DR, F, TECH, 'Union colleges staff the center; state colleges staff the rest. Amateur republics are treated as failed exams at both layers.');
  s(DR, F, REV, 'The union still dates from the overthrow. Some member republics never overthrew anyone and treat the calendar as a threat.');
  s(DR, F, CORP, 'National champions sit in the capital; regional combines sit in the states. Republican virtue is whoever endowed the school you attended.');
  s(DR, F, BUR, 'Citizens meet the republic twice: union paper and state paper. Rights exist in both, then wait in both.');
  s(DR, F, ECO, 'The commons are split. A union park and a state mill can occupy the same valley until a court picks a religion of land.');
  s(DR, F, MER, 'Magistracies at both layers want a cursus. The ambitious take the exam that travels; the rest take the county.');
  s(DR, F, CHA, 'The union republic has a face. Member republics have councils. When the face goes, the councils were already the government.');
  s(DR, F, LIB, 'Each layer exists to keep the other small. Double veto is how this republic defines freedom.');
  s(DR, F, PART, 'Assemblies at both layers. A citizen can be mandated locally and ignored nationally in the same week.');
  s(DR, F, ISO, 'The union republic does not go hunting monsters. A frontier republic may already be in a feud the capital calls illegal.');
  s(DR, F, PRAE, 'Two republics, two inner troops. “The people” is whoever’s guard holds the post office.');

  s(Dir, F, CS, 'Union ballots and canton ballots both hit an entrenched floor. A Tuesday majority cannot delete a minority just because two maps agreed to be angry.');
  s(Dir, F, POP, 'Every layer is a campaign. Federal initiatives and state initiatives stack until nobody remembers which no was binding.');
  s(Dir, F, MIL, 'The assembly votes war; state militias already moved. Officers call it preparation in two jurisdictions.');
  s(Dir, F, PAT, 'The floor votes itself stipends at both layers, then votes the taxes at neither. Clerks in the capital and the canton both improvise.');
  s(Dir, F, THEO, 'Sacred questions are banned from one ballot and reserved on the other. A profane union yes dies in a holy canton.');
  s(Dir, F, TECH, 'Citizens vote options framed by union institutes and state institutes that do not use the same model.');
  s(Dir, F, REV, 'Permanent assembly in the capital; some cantons never joined the square. Emergency votes bind the union and bounce off the holdouts.');
  s(Dir, F, CORP, 'Signature drives are cheaper in one state than in the union. Firms pick the cheaper floor and wait for preemption fights.');
  s(Dir, F, BUR, 'A passed union statute waits on canton rules, and the reverse. The people voted; the circulars are still meeting.');
  s(Dir, F, ECO, 'A canton can freeze a river the union ballot opened. Green initiatives travel whichever map is greener.');
  s(Dir, F, MER, 'The floor is popular at both layers; the pen is not. Drafting boards sit in two capitals and still look like the same exam.');
  s(Dir, F, CHA, 'A union voice can swing a national ballot and still lose a canton that never liked the voice.');
  s(Dir, F, LIB, 'The easiest double-yes is a double-no: both floors love forbidding a power. Doing things requires two turnouts.');
  s(Dir, F, PART, 'This is direct democracy with two jobs. Union juries and canton juries; politics is not a hobby, it is overtime.');
  s(Dir, F, ISO, 'A union pact must clear the union floor and then the border cantons. Entanglement dies of geography.');
  s(Dir, F, PRAE, 'Union guards decide which national ballots happen. Canton guards decide which local ones do. The people raise hands where they are allowed to stand.');

  s(Con, F, CS, 'Communal quotas are written into both the union charter and the state deals. A census fight is a constitutional crisis in two buildings.');
  s(Con, F, POP, 'Each street has a tribune; each state has another. Populists run against the cartel and still need it to keep the lights on in two layers.');
  s(Con, F, MIL, 'Mixed or captured armies exist at union and state. Officers are a communal veto that does not appear in either seating plan.');
  s(Con, F, PAT, 'Each bloc runs welfare in its states and demands a union top-up. Mixing the lists is how riots start, twice.');
  s(Con, F, TRAD, 'State quotas follow old houses; union quotas follow the same houses in nicer chairs.');
  s(Con, F, THEO, 'Personal status law is state-holy. The union cabinet’s job is keeping those courts from declaring each other void.');
  s(Con, F, TECH, 'Shared rails and water sit with mixed boards. Communal bosses still name the rest at both layers.');
  s(Con, F, REV, 'The truce is federal. Some member communities never signed it and treat every union budget as a ceasefire they might leave.');
  s(Con, F, CORP, 'Each community’s combines own a state and a union seat. A strike in one bloc halts two governments.');
  s(Con, F, BUR, 'Duplicate offices in duplicate layers. Peace is a filing system in two languages times two capitals.');
  s(Con, F, ECO, 'Rivers ignore communal states and the union map. Green rules become the only shared law or the next war.');
  s(Con, F, MER, 'Quotas set how many at each layer; exams set whom. An incompetent communal nominee is rejected as a breach of the federal deal.');
  s(Con, F, LIB, 'Both layers stay weak so no bloc can use them. The veto is the constitution, stacked.');
  s(Con, F, PART, 'Communal assemblies bind ministers in the statehouse and instruct the union slate the same night.');
  s(Con, F, ISO, 'Foreign patrons restart communal wars. The union forbids entanglement unless every bloc and every state signs, which means nothing signs.');
  s(Con, F, PRAE, 'Each community’s inner troops sit in “their” state. Union guards are supposed to be mixed. They are not, and everyone knows it.');

  s(Del, F, CS, 'Process is entrenched at both layers. A union bill that skipped state-mandated hearings is void even if the votes were there.');
  s(Del, F, POP, 'Union forums and state forums both chase authentic voice. Quiet evidence looks like elitism in two rooms.');
  s(Del, F, MIL, 'Officers sit in security hearings federally and locally. A deliberation that excludes the nearer garrison is called naïve, then ignored.');
  s(Del, F, PAT, 'Hearings at both layers end in a benefit. A policy with no stipend cannot survive either testimony stage.');
  s(Del, F, TRAD, 'State assemblies copy older councils; the union copies the states. Innovation wears custom twice.');
  s(Del, F, THEO, 'Scripture is public reason in the states and sometimes in the union. A bill that cannot be preached will not survive either hall.');
  s(Del, F, TECH, 'Briefing books come from union institutes and state institutes. Consensus looks like last year’s paper, cited in two formats.');
  s(Del, F, REV, 'The founding assembly never closed in the capital. Some states never opened it. Every statute is a debate the holdouts did not attend.');
  s(Del, F, CORP, 'Stakeholder tables at both layers include firms as neighborhoods. Deliberation that excludes capital is called incomplete, then defunded twice.');
  s(Del, F, BUR, 'Minutes, impact statements, comment periods — stacked. A decision without two paper trails is not a decision.');
  s(Del, F, ECO, 'Non-human interests get advocates in union and state rooms. Incomplete process is the green veto’s favorite phrase.');
  s(Del, F, MER, 'Sortition then training, twice. Random citizens still have to pass the briefing before either vote counts as informed.');
  s(Del, F, CHA, 'A union magnet fills the national circle. State circles have their own. The method looks like delay wherever the magnet is not standing.');
  s(Del, F, LIB, 'The only stacked consensus is “do not add a power.” Dual deliberation is a double brake.');
  s(Del, F, PART, 'Paid time off to attend union forums and state forums. Politics is a second job with two bosses.');
  s(Del, F, ISO, 'A treaty must survive the union floor and the border states’ hearings. By then the moment has passed twice.');
  s(Del, F, PRAE, 'Inner troops sit through the hearings they intend to void. Consensus the guard dislikes is incomplete at whichever layer they occupy.');

  loadDemocracyStacksMore();
}

function loadDemocracyStacksMore() {
  const RD = 'Representative Democracy';
  const Parl = 'Parliamentary Democracy';
  const Pres = 'Presidential Democracy';
  const DR = 'Democratic Republic';
  const Dir = 'Direct Democracy';
  const Con = 'Consociational Democracy';
  const Del = 'Deliberative Democracy';

  // ——— CONFEDERAL × STYLE ———
  s(RD, C, CS, 'Member polities elect their own houses under their own charters. The confederal diet cannot rewrite those charters; it can only beg.');
  s(RD, C, POP, 'Crowds are local. A tribune who tries to be confederal discovers each street already has a deputy and does not need another.');
  s(RD, C, MIL, 'Armies stay with the members. The diet’s “defence committee” is a liaison of officers who go home if the vote is boring.');
  s(RD, C, PAT, 'Benefits are member business. A confederal stipend is a rumor that dies at the first customs post.');
  s(RD, C, TRAD, 'Each member keeps its old benches. The diet is a courtesy among families who already rule at home.');
  s(RD, C, THEO, 'Holy members will not send a blasphemous file upward. The diet’s secular majority is a dinner party.');
  s(RD, C, TECH, 'Standards boards try to match gauges. Members implement, or do not, after the experts have gone home.');
  s(RD, C, REV, 'Some members are still in uprising; some never were. The diet’s emergency is not theirs.');
  s(RD, C, CORP, 'Firms incorporate where the member is cheapest. Confederal rules are a suggestion with a logo.');
  s(RD, C, BUR, 'The diet issues circulars; members issue their own. Citizens meet the nearer stamp.');
  s(RD, C, ECO, 'A member can save a river the diet wanted to sell. Confederal green law is a toast.');
  s(RD, C, MER, 'Each member filters office its own way. The diet’s “competence” is whoever the members bothered to send.');
  s(RD, C, CHA, 'A confederal face has no troops. Members clap, then govern as if the speech did not happen.');
  s(RD, C, LIB, 'The diet is not allowed to grow. That is the membership oath.');
  s(RD, C, PART, 'Local floors bind their envoys. A confederal vote can be undone before the envoys’ carriage leaves.');
  s(RD, C, ISO, 'Members already treat each other as abroad. True foreign policy is a stack of refusals.');
  s(RD, C, PRAE, 'There is no confederal guard worth the name. Each member’s regiment is the last argument, including against the diet.');

  s(Parl, C, CS, 'Member parliaments are the governments. A confederal cabinet is a committee of ambassadors whose charters say they can be recalled tonight.');
  s(Parl, C, POP, 'Premiers are local. A confederal tribune without a home house is a guest speaker.');
  s(Parl, C, MIL, 'Confidence is local; powder is local. The diet cannot fall a member’s cabinet and cannot arm itself.');
  s(Parl, C, PAT, 'Doles stay in the member budget. Confederal welfare is a communiqué.');
  s(Parl, C, TRAD, 'Member houses keep their openings. The diet copies the oldest ritual and still cannot tax.');
  s(Parl, C, THEO, 'A godly parliament will not grant supply to a profane diet. There is no other supply.');
  s(Parl, C, TECH, 'Member institutes run the files. Confederal tables are spreadsheets nobody is required to open.');
  s(Parl, C, REV, 'Revolutionary members treat the diet as a pause. Conservative members treat it as a fire. Neither funds it well.');
  s(Parl, C, CORP, 'Combines own member majorities. The diet is where they send junior lobbyists.');
  s(Parl, C, BUR, 'Ambassadors bring their own clerks. The confederal chancery is a coat rack.');
  s(Parl, C, ECO, 'A member house can protect a forest the diet mapped as timber. The map is not a law.');
  s(Parl, C, MER, 'Member frontbenches send whoever they can spare. Competence at the diet is accidental.');
  s(Parl, C, CHA, 'A magnetic speaker at the diet still needs a home majority. Without it they are applause.');
  s(Parl, C, LIB, 'Membership requires the diet stay toothless. A cabinet that invents a ministry is asking to be left.');
  s(Parl, C, PART, 'Local assemblies instruct envoys with binding mandates. The diet’s “majority” is a stack of instructions.');
  s(Parl, C, ISO, 'The diet cannot sign a war. Members who want quiet simply do not send ships.');
  s(Parl, C, PRAE, 'Guards belong to member cabinets. A confederal sitting ends when those guards are called home.');

  s(Pres, C, CS, 'Member presidents keep the armies. The confederal chair is a scheduler whose charter forbids surprise.');
  s(Pres, C, POP, 'Local palaces own the crowds. A confederal president on tour is a celebrity without a levy.');
  s(Pres, C, MIL, 'Commander-in-chief is a member title. The center’s “command” is a meeting request.');
  s(Pres, C, PAT, 'Clinics are member palaces’ gifts. The chair cuts ribbons on buildings they do not fund.');
  s(Pres, C, TRAD, 'Each member keeps its court ritual. The confederal oath is the thinnest costume in the room.');
  s(Pres, C, THEO, 'A holy member president will not implement a secular chair’s decree. There is no marshal to make them.');
  s(Pres, C, TECH, 'Member palaces hire the experts. The chair publishes a plan and hopes.');
  s(Pres, C, REV, 'Some member presidents still date from a rupture. The chair’s calendar is not theirs.');
  s(Pres, C, CORP, 'Firms incorporate under member presidents. The chair is a trade fair.');
  s(Pres, C, BUR, 'Decrees need member stamps. The chair’s signature is decorative.');
  s(Pres, C, ECO, 'A member can halt a river the chair named a union project. Names are not dams.');
  s(Pres, C, MER, 'Serious secretaries stay home. The chair’s cabinet is whoever could travel.');
  s(Pres, C, CHA, 'A magnetic chair still cannot fire a member president. The face stops at the customs house.');
  s(Pres, C, LIB, 'The chair exists to not build agencies. Members enforce that with absence.');
  s(Pres, C, PART, 'Member town votes bind member presidents, not the chair. Participation is local or it is pretend.');
  s(Pres, C, ISO, 'No member has to join a pact. Isolation is the default setting of a chair with no ships.');
  s(Pres, C, PRAE, 'Guards are member palace troops. The chair sleeps where they are allowed.');

  s(DR, C, CS, 'Sovereign republics pool a few files under contracts they can reopen. There is no crown and no center strong enough to become one.');
  s(DR, C, POP, 'Each republic performs its own people. A confederal crowd would be a contradiction in terms.');
  s(DR, C, MIL, 'Each republic keeps its force. Guardianship, if it exists, is a member hobby.');
  s(DR, C, PAT, 'Benefits are republican and local. Confederal citizenship is a passport, not a clinic.');
  s(DR, C, TRAD, 'Member republics keep founding families. The diet is a reunion.');
  s(DR, C, THEO, 'Civic creeds stay home. A confederal rite would be a schism.');
  s(DR, C, TECH, 'Colleges are member assets. Shared standards are voluntary exams.');
  s(DR, C, REV, 'Some republics are still founding. Others are tired. The diet cannot pick a Year One for both.');
  s(DR, C, CORP, 'Combines are member champions. The diet does not get to pick a national champion.');
  s(DR, C, BUR, 'Paperwork is local. Confederal forms are optional until a port requires them, then they are a fight.');
  s(DR, C, ECO, 'Commons are member commons. A diet map of a forest is a wish.');
  s(DR, C, MER, 'Cursus honorum is a member path. The diet offers no career worth the exam.');
  s(DR, C, CHA, 'A confederal face without a republic behind it is a toast.');
  s(DR, C, LIB, 'The contract exists to prevent a state. Members take that seriously.');
  s(DR, C, PART, 'Assemblies are member assemblies. Confederal participation is sending someone.');
  s(DR, C, ISO, 'Each republic already treats the others as foreign. True abroad is even quieter.');
  s(DR, C, PRAE, 'No confederal inner troop. Member guards can end the diet by not showing up.');

  s(Dir, C, CS, 'Each demos is supreme at home under its own entrenched rules. Confederal acts need another popular vote that often never comes.');
  s(Dir, C, POP, 'Every member is already a campaign. A confederal initiative is a fourth pamphlet nobody reads.');
  s(Dir, C, MIL, 'Member assemblies vote their own wars. The diet’s war vote is fan fiction.');
  s(Dir, C, PAT, 'Member floors vote their own stipends. Confederal charity is a collection plate.');
  s(Dir, C, THEO, 'Sacred bans are member bans. A confederal ballot on doctrine is how you get a walkout.');
  s(Dir, C, TECH, 'Options are framed at home. Confederal choices arrive pre-rejected.');
  s(Dir, C, REV, 'Some floors never left the square. Others did. The diet cannot schedule both moods.');
  s(Dir, C, CORP, 'Signature money is local. Firms do not bother buying a diet that cannot bind.');
  s(Dir, C, BUR, 'Member circulars implement member votes. Confederal yeses wait in a tray.');
  s(Dir, C, ECO, 'A member floor can save a river the diet named. Names are not votes.');
  s(Dir, C, MER, 'Drafting skill stays home. The diet’s text is whoever had a free afternoon.');
  s(Dir, C, CHA, 'A voice that carries in one assembly is noise in another. Confederal charisma does not travel.');
  s(Dir, C, LIB, 'The easiest confederal result is a no. Members like that.');
  s(Dir, C, PART, 'People already have a floor at home. Asking them to also be confederal is how you empty both rooms.');
  s(Dir, C, ISO, 'Pacts die at member floors. The diet is an isolation machine by design.');
  s(Dir, C, PRAE, 'Guards are member guards. They decide whether a confederal ballot even gets a room.');

  s(Con, C, CS, 'The blocs are sovereign and the quotas are treaties. There is no court above a community that can make it sit.');
  s(Con, C, POP, 'Each bloc’s street is its own. A confederal tribune is a guest of four crowds.');
  s(Con, C, MIL, 'Each community keeps force. The diet’s mixed brigade exists on paper and on parade.');
  s(Con, C, PAT, 'Welfare is communal and local. Mixing lists across members is how the truce ends.');
  s(Con, C, TRAD, 'Old houses are member houses. The diet is a courtesy among cartels.');
  s(Con, C, THEO, 'Holy courts are member courts. Confederal personal status law would be a war.');
  s(Con, C, TECH, 'Shared water is a treaty among engineers who go home to different bosses.');
  s(Con, C, REV, 'Some blocs still think the war is on. The diet’s “settlement” is their ceasefire, not their peace.');
  s(Con, C, CORP, 'Combines are communal and member-bound. A confederal market is a rumor.');
  s(Con, C, BUR, 'Peace is duplicate offices inside each member. The diet adds a third language and no power.');
  s(Con, C, ECO, 'Rivers ignore members and blocs. Green treaties last until a community needs a mill.');
  s(Con, C, MER, 'Each bloc filters its own envoys. The diet cannot reject an incompetent without insulting a people.');
  s(Con, C, LIB, 'The whole point of the league is that no center can be used. Members enforce thinness with absence.');
  s(Con, C, PART, 'Communal halls bind envoys before they travel. The diet is a reading of instructions.');
  s(Con, C, ISO, 'Foreign patrons are how the war restarts. Nothing signs unless every bloc in every member signs.');
  s(Con, C, PRAE, 'Inner troops are communal and member-owned. A diet sitting ends if one family calls theirs home.');

  s(Del, C, CS, 'Each member’s process is its constitution. The diet cannot declare a hearing finished for them.');
  s(Del, C, POP, 'Authentic voice is local. Confederal forums feel like someone else’s town.');
  s(Del, C, MIL, 'Member garrisons sit in member hearings. The diet’s security table is empty chairs with ranks.');
  s(Del, C, PAT, 'Benefits are argued at home. Confederal testimony produces communiqués, not stipends.');
  s(Del, C, TRAD, 'Member councils keep speaking order. The diet’s facilitator is a foreign custom.');
  s(Del, C, THEO, 'Public reason is member scripture. A diet that skips it is illegitimate at home.');
  s(Del, C, TECH, 'Briefing books stay with member institutes. Shared papers are voluntary reading.');
  s(Del, C, REV, 'Some members still debate the uprising. The diet’s “enough talking” is a fighting word there.');
  s(Del, C, CORP, 'Stakeholder tables are member tables. Firms do not fund a diet that cannot award a contract.');
  s(Del, C, BUR, 'Two comment periods, then a third nobody files. Process without a state is a hobby.');
  s(Del, C, ECO, 'A member can talk a forest into protection the diet never voted. That is still the law there.');
  s(Del, C, MER, 'Training for sortition is a member budget. The diet gets whoever could travel.');
  s(Del, C, CHA, 'A magnet at the diet does not own member circles. Applause, then the real session at home.');
  s(Del, C, LIB, 'Members use deliberation to refuse powers. The diet’s calendar is a list of nos.');
  s(Del, C, PART, 'People already attend at home. Confederal attendance is a tax on the same bodies.');
  s(Del, C, ISO, 'Treaties die in member hearings. The diet is where urgency goes to sleep.');
  s(Del, C, PRAE, 'Member guards decide which hearings happen. The diet borrows a room and hopes.');
}

loadDemocracyStacks();
