import { NONE, UNITARY, ZYTHERA, put } from './govOperating.store';

const U = UNITARY;
const F = 'federal';
const C = 'confederal';
const Y = 'federacy / asymmetrical federation';
const I = 'imperial / hegemonic';
const N = NONE;
const CS = 'Constitutional / Limited';
const POP = 'Populist';
const MIL = 'Military-Influenced';
const PAT = 'Paternalist / Welfare-First';
const TRAD = 'Traditional / Hereditary';
const THEO = 'Theocratic Influence';
const TECH = 'Technocratic';
const REV = 'Revolutionary / Provisional';
const CORP = 'Corporate / Business Elite';
const BUR = 'Bureaucratic';
const ECO = 'Ecological / Green-Influenced';
const MER = 'Meritocratic';
const CHA = 'Charismatic Leader Focus';
const PRAE = 'Praetorian / Security-State';
const LIB = 'Libertarian / Minimal-State';
const PART = 'Participatory / Deliberative';
const ISO = 'Isolationist';

function z(sub: string, terr: string, style: string, text: string) {
  put(ZYTHERA, sub, terr, style, text);
}

export function loadZytheraStacks() {
  const HC = 'Hive Council / One-Party Elite Rule';
  const CA = 'Caste Oligarchy';
  const TC = 'Theocratic Council';
  const GE = 'Gerontocracy';
  const Q = 'Absolute Monarchy / Queen-Rule';
  const TY = 'Tyranny / Personalist Rule';
  const AT = 'Absolute Theocracy';
  const SW = 'Hive Collapse / Swarm Anarchy';

  // ——— Hive Council: party-chorus, hive-flavored ———
  z(HC, U, CS, 'A charter of the song hangs in every chamber. The council then retunes any verse that would bind it. Rights are a harmony that can be scored out.');
  z(HC, U, POP, 'The chorus is bussed as “the hive.” Drones who miss the pitch are not an opposition; they are a wrong note.');
  z(HC, U, MIL, 'Warrior caste sits in the council as if it were a civilian hat. The song has a sting. A purely brood-scholar secretary is a rumor the garrison already filed.');
  z(HC, U, PAT, 'Rations are a dossier and a scent. Loyalty is a benefit tier; hunger is how the chorus keeps time.');
  z(HC, U, TRAD, 'Founding broods hold the chairs. The council-song is a family tree with better acoustics.');
  z(HC, U, THEO, 'Doctrine is the file. A secretary who drifts is not a federalist; she is a molt that will not happen.');
  z(HC, U, TECH, 'The five-year comb is drawn by caste-savants. Campaigns argue scent; the tables already know the cells.');
  z(HC, U, REV, 'The seizure of the song never adjourned. Emergency is the constitution.');
  z(HC, U, CORP, 'Party-holdings are the comb. A private fortune is a franchise of the nearest committee-brood.');
  z(HC, U, BUR, 'Cadre files, two stamps, a pheromone trail. Promotion is a form that smells like consent.');
  z(HC, U, ECO, 'Land targets are plan cells. A frozen forest is a dispute in the comb, not a park.');
  z(HC, U, MER, 'Hive school, then the caste exam. There is no other ladder.');
  z(HC, U, CHA, 'One name sits the banner. When that scent dies, the council discovers it was a chorus.');
  z(HC, U, PRAE, 'Interior cars that smell like the crypt. A caste card does not stop a union night.');
  z(HC, U, LIB, 'The council boasts it stays out of the cell. Then the block warden visits. Minimal is a slogan in the file.');
  z(HC, U, PART, 'Work-comb meetings soak the talk. The politburo-brood is not on the agenda.');
  z(HC, U, ISO, 'The world is contamination. The border is a hygiene rule, not a policy debate.');

  z(HC, F, CS, 'Sister hives swear the same scored rights. The council then retunes any nest that sings a binding verse. Federal paper, one exception scent.');
  z(HC, F, POP, 'Local choruses bus for the same hymn. Federalism is two rallies with one pitch.');
  z(HC, F, MIL, 'Commissar-warriors sit in nest and union. A civilian secretary is a rumor twice.');
  z(HC, F, PAT, 'Rations are union and nest, same dossier. Loyalty follows you across the internal comb.');
  z(HC, F, TRAD, 'Founding broods hold nest posts and council posts. Harmony is a family tree with two letterheads.');
  z(HC, F, THEO, 'Doctrine is the federal file. A nest that drifts is retuned as heresy.');
  z(HC, F, TECH, 'Union tables, nest tables, one school. The five-year comb has counties.');
  z(HC, F, REV, 'Both layers still date from the seizure of the song. Emergency is federal and local.');
  z(HC, F, CORP, 'Holdings at both layers. A fortune is a franchise of whichever committee-brood is nearer.');
  z(HC, F, BUR, 'Cadre files in two stacks. Promotion needs both stamps and the right scent.');
  z(HC, F, ECO, 'Land targets union; implementation nest. A frozen forest is a plan dispute.');
  z(HC, F, MER, 'Hive school, then the nest exam, or the reverse. No other ladder in either layer.');
  z(HC, F, CHA, 'The banner scent sits in the capital. Nest secretaries orbit it and become a chorus when it dies.');
  z(HC, F, PRAE, 'Interior at council and nest. A nest card does not stop a union night.');
  z(HC, F, LIB, 'Thin talk in the provinces. Wardens still visit. Minimal has two addresses.');
  z(HC, F, PART, 'Work-comb meetings at both layers. The council-brood is on neither agenda.');
  z(HC, F, ISO, 'Contamination law at both layers. Border nests are just more interior.');

  z(HC, C, N, 'Sister councils keep their own songs. The liaison cannot even schedule the hymns. Harmony is a toast.');
  z(HC, C, POP, 'Each nest buses its own chorus. A confederal tribune is a guest of several pitches.');
  z(HC, C, MIL, 'Warrior castes stay home. Confederal defence is a parade that may not happen.');
  z(HC, C, PAT, 'Rations are nest business. The liaison does not feed.');
  z(HC, C, TRAD, 'Each founding brood rules its nest. The diet is a reunion with minutes.');
  z(HC, C, THEO, 'Doctrine is local enough to schism. The diet cannot excommunicate a nest-song.');
  z(HC, C, TECH, 'Each council-hive plans at home. Shared gauges are optional combs.');
  z(HC, C, REV, 'Some nests are still seizing the song. The diet’s Year One is not theirs.');
  z(HC, C, CORP, 'Holdings stay in the nest. Confederal combines are a rumor.');
  z(HC, C, BUR, 'Cadre files do not travel. The diet has no drawer.');
  z(HC, C, ECO, 'A nest can freeze a forest the diet mapped. The map is not a committee.');
  z(HC, C, MER, 'Schools are nest schools. The diet offers no career.');
  z(HC, C, CHA, 'A confederal scent without a nest-party behind it is applause.');
  z(HC, C, PRAE, 'Cars belong to nest interiors. The diet sleeps where it is allowed.');
  z(HC, C, LIB, 'The diet is not allowed to grow. Membership is thinness; thickness stays home.');
  z(HC, C, PART, 'Comb meetings bind envoys. The diet is a reading of instructions.');
  z(HC, C, ISO, 'Nests already treat each other as abroad. True foreign is quieter still.');
  z(HC, C, CS, 'Each nest hangs scored rights it has already suspended. The diet’s charter is a prettier score nobody sings.');

  z(HC, Y, N, 'Ordinary nests sing the council-song. One brood kept a side letter and a private pitch. Harmony has a hole.');
  z(HC, Y, POP, 'Ordinary nests bus for the party-chorus. The special brood already won and does not need the bus.');
  z(HC, Y, MIL, 'Union commissars, except the brood that kept its own sting. A memo there is a foreign act.');
  z(HC, Y, PAT, 'Dossiers skip, or only exist in, the footnote comb.');
  z(HC, Y, TRAD, 'The exception is a founding brood that never merged its scent.');
  z(HC, Y, THEO, 'A heresy with a side letter. The center has not digested it.');
  z(HC, Y, TECH, 'The five-year comb has a blank province on purpose.');
  z(HC, Y, REV, 'Emergency in the ordinary map. The footnote files it under not-our-seizure.');
  z(HC, Y, CORP, 'The privileged comb answers to a different committee-brood.');
  z(HC, Y, BUR, 'Ordinary circulars and exemption circulars. Both say party-song.');
  z(HC, Y, ECO, 'The footnote can freeze a forest the plan already counted.');
  z(HC, Y, MER, 'Hive school, except the exception’s cadre is named in the letter.');
  z(HC, Y, CHA, 'The banner stops at a league that never hung the scent.');
  z(HC, Y, PRAE, 'Union cars knock. The footnote’s cars open, or do not.');
  z(HC, Y, LIB, 'Thinness is for the ordinary nests. The exception may be a denser little hive by right.');
  z(HC, Y, PART, 'Comb meetings in the ordinary map. The footnote may not send a slate.');
  z(HC, Y, ISO, 'The hive stays closed — except the footnote’s cousins, already in the letter.');
  z(HC, Y, CS, 'Scored rights, plus a hole shaped like a brood. Exception as well as suspension.');

  z(HC, I, CS, 'The core’s score binds the council. It does not bind lesser nests, which live under governors and enabling verses the charter calls “outer comb.”');
  z(HC, I, POP, 'The core chorus is the people. Outer broods get the hymn without the vote, which they did not have anyway.');
  z(HC, I, MIL, 'Party-sting at home; governors in armor in the marches. Same school, colder climate.');
  z(HC, I, PAT, 'Core dossiers include clinics. Subject dossiers include grain and a curfew scent.');
  z(HC, I, TRAD, 'Founding broods of the core staff the civilizing mission. Outer notables are pupils.');
  z(HC, I, THEO, 'Doctrine is exported as civilization. Outer rites are errors.');
  z(HC, I, TECH, 'Core tables plan other people’s rivers.');
  z(HC, I, REV, 'The seizure liberated the core. The marches were next on the list.');
  z(HC, I, CORP, 'Party holdings extract from client nests. Solidarity is a metropolitan word.');
  z(HC, I, BUR, 'Civic files at home; pass-scents abroad.');
  z(HC, I, ECO, 'Core parks; provincial pits. The comb has a center.');
  z(HC, I, MER, 'Cadre exams for the core. Translators for the rest.');
  z(HC, I, CHA, 'The banner name is printed on offices that never sat the congress-comb.');
  z(HC, I, PRAE, 'Interior at home; occupation at the edge.');
  z(HC, I, LIB, 'Thin talk at home, thick governors abroad. Liberty does not ship.');
  z(HC, I, PART, 'Comb meetings for the core. Subject nests get notified.');
  z(HC, I, ISO, 'The world is contamination. Outer lands are already in the file as interior dirt. No embassy, only governors, and the border beyond them is hygiene.');

  loadZytheraStacks2();
}

function loadZytheraStacks2() {
  const CA = 'Caste Oligarchy';
  const TC = 'Theocratic Council';
  const GE = 'Gerontocracy';
  const Q = 'Absolute Monarchy / Queen-Rule';
  const TY = 'Tyranny / Personalist Rule';
  const AT = 'Absolute Theocracy';
  const SW = 'Hive Collapse / Swarm Anarchy';

  // Caste oligarchy
  z(CA, U, CS, 'Ranks are the constitution. A charter lists mobility the high castes have already molt-blocked. Paper explains why the ladder does not move.');
  z(CA, U, POP, 'Low castes are bussed as the hive’s voice. They chant. They do not sit.');
  z(CA, U, MIL, 'Warrior caste is not influence; it is a rung with a sting. Scholar-castes draft around it.');
  z(CA, U, PAT, 'High castes feed dependents and call it the pattern. Eviction is a molt order.');
  z(CA, U, TRAD, 'This is the thing itself: fixed broods, fixed mouths, precedent in the comb.');
  z(CA, U, THEO, 'Caste is doctrine. A mixed pairing is a heresy that does not hatch.');
  z(CA, U, TECH, 'Savant-caste runs the numbers. Low caste is a labor input in the model.');
  z(CA, U, REV, 'A new rung was declared after a rupture. The old rungs are still armed.');
  z(CA, U, CORP, 'High-caste holdings are the economy. Low caste invoices as inventory.');
  z(CA, U, BUR, 'Enrollment in the caste book is the only permit. Lesser broods wait in a second queue.');
  z(CA, U, ECO, 'Land law is high-caste game law. A mill fights a court of peers who do not molt.');
  z(CA, U, MER, 'Exams exist for the working offices. The speaking chairs are caste, not score.');
  z(CA, U, CHA, 'One high-caste name is the pattern. When it dies, the rungs remain.');
  z(CA, U, PRAE, 'Household sting around the high chairs. Nights are a caste privilege.');
  z(CA, U, LIB, 'The state stays thin for those who already sit. Thickness is for everyone else.');
  z(CA, U, PART, 'Low castes may attend. They do not close the session.');
  z(CA, U, ISO, 'Foreign mixing is a molt that must not happen. The border is a breeding rule.');

  z(CA, F, N, 'Each nest keeps its ladder, then sends the highest. Low castes never travel as speakers. Federalism is a union of summits.');
  z(CA, F, POP, 'Nests bus their lower rungs for the union hymn. Seats still belong to the highest who arrived.');
  z(CA, F, MIL, 'Warrior rungs at nest and union. Commands follow pedigree at both layers.');
  z(CA, F, PAT, 'Crested clinics in the nests; a grander comb in the capital. Two parents, one blood-caste.');
  z(CA, F, TRAD, 'Precedence in two chambers. The season is federal; the nest still dines first.');
  z(CA, F, THEO, 'Altars local, pairings union. A house that loses either loses the nest.');
  z(CA, F, TECH, 'Steward-castes run nests; union savants run the diet. Fools lose to cousins who can count, twice.');
  z(CA, F, CHA, 'A magnetic brood in the capital. Nests keep their own high names.');
  z(CA, F, PRAE, 'Household sting around the capital and around each great brood. Nights are local.');
  z(CA, F, ISO, 'Border nests may still marry out. The diet pretends mixing is a closed file.');
  z(CA, F, CS, 'Two scored ladders. A union majority cannot molt a nest’s reserved rungs.');
  z(CA, C, N, 'Sovereign ladders. The diet is a courtesy among high castes who already rule at home.');
  z(CA, C, TRAD, 'This is a league of blood-caste. Minutes are guest-right.');
  z(CA, C, POP, 'Each nest feeds its own lower rungs. A confederal tribune is a guest at someone else’s comb.');
  z(CA, C, ISO, 'Each ladder already treats the next nest as abroad.');
  z(CA, C, CHA, 'A diet face without retainers is a toast.');
  z(CA, Y, N, 'Ordinary nests share a ladder-union. One march kept thicker high justice in a side comb.');
  z(CA, Y, TRAD, 'The exception is a leftover high brood. Ordinary rungs work around a chair they cannot fill.');
  z(CA, I, N, 'High castes of the core; outer species as lower rungs of a map. No shared molt, no shared seat.');
  z(CA, I, POP, 'Core houses tour as protectors. Outer broods learn the crest as a tax.');
  z(CA, I, MIL, 'Core retainers occupy. Outer levies are client rungs.');
  z(CA, I, PAT, 'Paternal duty at home; extraction abroad, still called pattern.');
  z(CA, I, TRAD, 'The empire is a family tree with worse cousins.');
  z(CA, I, ISO, 'The high houses married the map already. New foreign matches are vulgar. Outer notables are in-laws who do not get a season in the comb.');

  // Theocratic council (hive)
  z(TC, U, CS, 'Canon includes earthly limits. The brood-college interprets every clause as already fulfilled by molt-obedience.');
  z(TC, U, POP, 'Revivals are bussed as the divine hive. Drones chant. Doctrine does not ask them.');
  z(TC, U, MIL, 'Templar-caste sits with the college. A scholarly majority does not survive a campaign season.');
  z(TC, U, PAT, 'Alms queues. Unbelief is a benefits decision that smells like a sermon.');
  z(TC, U, TRAD, 'The oldest commentary still wins. Precedent is liturgy.');
  z(TC, U, THEO, 'The college is the law, then keeps an influence chapel for the fiction of a civil comb. There is not one.');
  z(TC, U, TECH, 'Sacred sciences. A model that contradicts creed is an incomplete molt.');
  z(TC, U, REV, 'The last purification never closed. Emergency is a feast day.');
  z(TC, U, CORP, 'Temple holdings. Virtue is a trademark with better incense.');
  z(TC, U, BUR, 'Dispensations. Grace is rationed as paper and scent.');
  z(TC, U, ECO, 'Sacred groves. A mill that poisons a well is a heresy with a smokestack.');
  z(TC, U, MER, 'Exams for clergy. The chairs are still a college of blood-caste.');
  z(TC, U, CHA, 'A prophet-brood in the college. When her scent stops, they are drones in hats.');
  z(TC, U, PRAE, 'Inquisition that smells like the crypt. A night can change the creed.');
  z(TC, U, LIB, 'They claim the soul, not the market — then tithe both.');
  z(TC, U, PART, 'Congregations vote feast days. Creed is not congregational.');
  z(TC, U, ISO, 'True faith is a geography. Beyond the last converted nest is pollution.');
  z(TC, F, N, 'Diocese-nests under one college-song. A nest that sings off-key is retuned as heresy, not outvoted.');
  z(TC, F, POP, 'Revivals local; the union synod pretends they were always doctrine.');
  z(TC, F, MIL, 'Templars at both layers. Scholarly majorities die twice.');
  z(TC, F, PAT, 'Alms in diocese and union. Unbelief is a benefits decision twice.');
  z(TC, F, TRAD, 'Canon local and federal. The oldest commentary still wins.');
  z(TC, F, THEO, 'The college is the law in both palaces, then an influence office for people who think there is a secular file. Pulpit twice.');
  z(TC, F, BUR, 'Dispensations in two chanceries. Grace rationed twice.');
  z(TC, F, CHA, 'A prophet in the union college. Regional synods keep their own saints.');
  z(TC, F, PRAE, 'Inquisition cars federally and in the nest. A nest card is not a blessing.');
  z(TC, C, N, 'Autocephalous holy nests. The diet cannot name a heresy that sticks.');
  z(TC, C, TRAD, 'Each house keeps rite. Minutes are courtesy among altars.');
  z(TC, C, POP, 'Each church-brood buses its own revival. Confederal piety is a hymnbook nobody shares.');
  z(TC, C, THEO, 'Each synod is already a church-state. The diet’s extra holiness is a title they skip.');
  z(TC, Y, N, 'Ordinary college, plus a stricter rite fenced by treaty.');
  z(TC, Y, TRAD, 'The footnote is holier, by paper. Ordinary nests live under the milder verse.');
  z(TC, I, N, 'Core college; outer conversions. Outer altars are errors until they rebel.');
  z(TC, I, POP, 'Core revivals; outer conversions. The hymn is exported.');
  z(TC, I, MIL, 'Templars at home; missions with soldiers in the marches.');
  z(TC, I, THEO, 'Canon at home, missions abroad, and a third office called influence so nobody has to say occupation.');
  z(TC, I, ISO, 'Missions stop at the last converted nest. The marches exist to be the last fence. Nothing else comes in.');

  // Gerontocracy hive
  z(GE, U, CS, 'Limits exist on the wall. The oldest queens interpret them as already waited-out. Youth is a clause that has not matured.');
  z(GE, U, POP, 'Elders speak as grandparents of the comb. The young chant. They do not close.');
  z(GE, U, MIL, 'Ancient warrior-mothers keep the sting. Young soldiers wait through lives that would be careers.');
  z(GE, U, PAT, 'Care for the aged is the first duty, which is convenient.');
  z(GE, U, TRAD, 'Precedent is the whole machine. Delay is policy.');
  z(GE, U, THEO, 'The oldest are closest to the first Queen. Doctrine is seniority.');
  z(GE, U, TECH, 'Young savants run tables. They will not take the dais.');
  z(GE, U, REV, 'A rupture that put new old ones in chairs. The previous old ones are still armed with memory.');
  z(GE, U, CORP, 'Holdings accrue to those who waited. New fortunes look like theft of time.');
  z(GE, U, BUR, 'Forms take years. That is the point.');
  z(GE, U, ECO, 'Land is what the dead planted. A mill waits in committee until the planters’ daughters are old.');
  z(GE, U, MER, 'A young passer of the exams can run a bureau. They will not take the speaking chair. Age keeps the dais; merit keeps the files moving underneath it.');
  z(GE, U, CHA, 'One ancient name. When it dies, the next ancient name was already sitting.');
  z(GE, U, PRAE, 'Household of the oldest. A night can skip a generation.');
  z(GE, U, LIB, 'Thin ministries; thick waiting. Minimal state means minimal youth.');
  z(GE, U, PART, 'The young may attend. They do not close the session.');
  z(GE, U, ISO, 'The elders remember one disastrous embassy. Ports stay shut. Time is a border.');
  z(GE, F, N, 'Elders in the union and the nests. Delay is national and local policy.');
  z(GE, F, POP, 'Grandparents of two maps. Two crowds, one waiting room.');
  z(GE, F, PAT, 'Care for the aged in both budgets, which is convenient twice.');
  z(GE, F, TRAD, 'Precedent stacked. Nothing urgent is federal or local.');
  z(GE, F, MER, 'A young passer runs a nest bureau. They will not take the union dais, or the nest one.');
  z(GE, F, CHA, 'One ancient scent in the capital. Nest elders keep sitting when it dies.');
  z(GE, C, N, 'Sovereign councils of brood-mothers. Nothing urgent is confederal.');
  z(GE, C, TRAD, 'Each nest waits in its own way. The diet is a nap with minutes.');
  z(GE, Y, N, 'Ordinary elders, plus a footnote whose chairs are older still and named.');
  z(GE, Y, MER, 'Exams in the ordinary comb. The footnote’s chairs are aged and named.');
  z(GE, I, N, 'The core’s old are the hive. Outer young are children in the law.');
  z(GE, I, PAT, 'The core’s old are cared for. Outer young work.');
  z(GE, I, ISO, 'The elders closed the ports. Client provinces are children, not foreigners, and children do not receive guests.');

  loadZytheraQueens();
}

function loadZytheraQueens() {
  const Q = 'Absolute Monarchy / Queen-Rule';
  const TY = 'Tyranny / Personalist Rule';
  const AT = 'Absolute Theocracy';
  const SW = 'Hive Collapse / Swarm Anarchy';

  z(Q, U, CS, 'There is a charter, and the Queen signs it in public. Then she issues the next edict anyway. Courts explain why this exception was always the scent.');
  z(Q, U, POP, 'The hive is bussed as her people. The square chants a name that does not ask it.');
  z(Q, U, MIL, 'The sting is hers. Officers exist to smell like obedience.');
  z(Q, U, PAT, 'Household kindness. You are fed, and you are hers.');
  z(Q, U, TRAD, 'Blood and molt-line. The Queen is the state because the dead said so.');
  z(Q, U, THEO, 'Anointing is a work shift. Pulpit and throne are one comb.');
  z(Q, U, TECH, 'Savants count for her pleasure. A table that contradicts the edict is broken.');
  z(Q, U, REV, 'This Queen still dates from a rupture. Emergency is the court calendar.');
  z(Q, U, CORP, 'Royal companies. The crown hangs boards that look like cabinets.');
  z(Q, U, BUR, 'Chancery scent. Edicts travel as paper until a viceroy sits on them.');
  z(Q, U, ECO, 'The land is the Queen’s game. A mill fights a household court.');
  z(Q, U, MER, 'Capable stewards serve at pleasure. Exams do not make a Queen.');
  z(Q, U, CHA, 'She is the regime. Furniture until the funeral includes every minister.');
  z(Q, U, PRAE, 'Household guard. Dawn can change a realm without changing the comb’s name.');
  z(Q, U, LIB, 'Thin ministries, thick household. Minimal state means maximal Queen.');
  z(Q, U, PART, 'Petitions if she is bored. The floor is a pageant.');
  z(Q, U, ISO, 'The court does not receive foreign queens. Isolation is etiquette.');

  z(Q, F, CS, 'Charters in the daughter-nests, signed by a Queen who then edicts. Courts explain the exception twice.');
  z(Q, F, POP, 'Daughter-queens bus crowds for the top scent. Two rallies, one name.');
  z(Q, F, PAT, 'Household kindness in the capital; viceroys copy it. Two parents, one blood.');
  z(Q, F, TRAD, 'Oaths to one person, courts in each nest. Federal in map, personal in kneeling.');
  z(Q, F, THEO, 'Altars in the nests; one anointing. A viceroy who loses the pulpit loses the levy.');
  z(Q, F, BUR, 'Chancery and provincial chanceries. Edicts travel as paper and scent.');
  z(Q, F, CHA, 'This Queen is the regime. Viceroys are furniture until the funeral.');
  z(Q, F, PRAE, 'Household guard in the capital; viceroys’ sting at home. Dawn can change a nest without changing the crown.');
  z(Q, F, MIL, 'The commander is the Queen. Nest militias pretend they have another phone.');
  z(Q, C, N, 'Sovereign daughter-queens swear to a high Queen they will not actually obey. The crown tours; the armies stay home.');
  z(Q, C, CS, 'Local queens keep charters signed and ignored at home. The high Queen’s parchment is for festivals.');
  z(Q, C, POP, 'Each court feeds its own comb. The touring crown is a guest of crowds it does not own.');
  z(Q, C, MIL, 'Levies stay with the daughters. The high Queen blesses wars she cannot start.');
  z(Q, C, TRAD, 'Blood locally, courtesy at the diet. Custom does not travel upward.');
  z(Q, C, CHA, 'The magnetic house is a member court. A high Queen who tries to be the only scent learns about retainers.');
  z(Q, C, PRAE, 'Household troops sleep in provincial palaces. Dawn can end a diet without touching a throne.');
  z(Q, C, ISO, 'Each daughter already treats the next as a foreign court. The high Queen cannot open the league to the sea.');
  z(Q, Y, N, 'The realm is the Queen’s, except a march with old high justice she has not torn.');
  z(Q, Y, TRAD, 'Ordinary kneeling, plus a leftover brood-crown in the footnote.');
  z(Q, Y, CS, 'A charter the Queen signs, plus a footnote she has not torn. Two kinds of exception.');
  z(Q, Y, CHA, 'Most of the map is her will. The footnote still has a machine she has not staffed with cousins.');
  z(Q, I, N, 'This is a hive empire. Subject species and lesser nests exist to feed a court they will never smell as equals.');
  z(Q, I, TRAD, 'The court is the core. The rest is possession. No shared blood, no shared vote.');
  z(Q, I, PAT, 'Grain at home; tribute abroad, still called paternal.');
  z(Q, I, THEO, 'Divine right exported as mission.');
  z(Q, I, CORP, 'Royal companies collect the marches.');
  z(Q, I, CHA, 'One person is the empire. Satraps are names on a whim.');
  z(Q, I, CS, 'The core’s charter binds the court on paper. The marches live under governors the constitution calls outer comb.');
  z(Q, I, ISO, 'The court does not receive foreign queens. Possessions are household rooms. Isolation is etiquette: the world waits outside a door that is already an empire.');
  z(Q, I, POP, 'Core combs chant her name. Outer nests learn it as a tax.');
  z(Q, I, PRAE, 'Household at home; occupation at the edge.');

  z(TY, U, CS, 'Paper limits were written for offices. This hive is a person. The charter is quoted when it flatters her scent.');
  z(TY, U, POP, 'The chorus exists to say her name. Crowds are proof of a relationship.');
  z(TY, U, MIL, 'The sting is personal. Rank is whoever she looked at last.');
  z(TY, U, PAT, 'Clinics where the motorcade will smell; nothing where it will not.');
  z(TY, U, TRAD, 'Kin if she says so. Blood is a mood.');
  z(TY, U, THEO, 'Worship is optional branding. Disloyalty is still a molt that does not happen.');
  z(TY, U, TECH, 'Counters she likes. Tables she does not are broken.');
  z(TY, U, REV, 'The uprising is her biography. Year One is her birthday.');
  z(TY, U, CORP, 'Holdings are gifts. Boards are friends.');
  z(TY, U, BUR, 'First names on every form. Offices are furniture.');
  z(TY, U, ECO, 'The land is a mood. A forest lives if she is pleased.');
  z(TY, U, MER, 'Talent is whoever she trusts this week.');
  z(TY, U, CHA, 'The country is a relationship. No relationship, no hive.');
  z(TY, U, PRAE, 'Bodyguards. Ministers learn the news from a door.');
  z(TY, U, LIB, 'No ministries except her. Thinness is a private body.');
  z(TY, U, PART, 'Sit-downs if she wants witnesses.');
  z(TY, U, ISO, 'Friends may visit; states may not. The closed border is personal.');
  z(TY, F, N, 'Friends as nest-governors. First names on two maps. No relationship, no province.');
  z(TY, F, POP, 'Friends bus crowds. Federalism is two rallies, one scent.');
  z(TY, F, CHA, 'The hive is a relationship at both layers.');
  z(TY, F, PRAE, 'Bodyguards in the capital and in each friend’s house.');
  z(TY, F, CS, 'Paper for offices. This is first names. Quoted in both capitals when it flatters.');
  z(TY, C, N, 'Local usurper-broods run patches as private bodies. They keep a shared celebrity so nobody admits the league is a truce.');
  z(TY, C, CHA, 'The magnetic person is a provincial boss. Sharing a celebrity at the center is how they avoid admitting the truce.');
  z(TY, C, PRAE, 'Bodyguards are local households. The diet ends when a crew comes to fetch someone.');
  z(TY, Y, N, 'Most regions are property. One corner still has a machine.');
  z(TY, Y, CHA, 'Most of the map is a will. The footnote still has a machine the palace has not staffed with cousins.');
  z(TY, I, N, 'Companions as satraps. Outer lands are gifts, revoked the same way.');
  z(TY, I, CHA, 'Satraps are companions. Outer lands are gifts.');
  z(TY, I, PAT, 'Clinics where the motorcade will see, including nowhere abroad that it will not.');
  z(TY, I, ISO, 'Friends may visit; states may not. Satrapies are gifts, not countries. The marches live inside that friendship.');

  z(AT, U, CS, 'Canon includes earthly limits. The Queen-god interprets them as already fulfilled by labor-prayer.');
  z(AT, U, POP, 'Liturgy is the crowd. Unbelief is a wrong note in a hymn that is also a shift.');
  z(AT, U, MIL, 'Sacred sting. Assessment after the hymn.');
  z(AT, U, PAT, 'Alms and hunger as sermon.');
  z(AT, U, TRAD, 'The first Queen is still at work in the rite.');
  z(AT, U, THEO, 'She is the god and the state, then keeps an influence chapel for the fiction of a civil comb.');
  z(AT, U, TECH, 'Sacred sciences. A contradicting table is heresy.');
  z(AT, U, REV, 'Purification never closed. Emergency is a feast.');
  z(AT, U, CORP, 'Temple holdings. Tithe is an invoice.');
  z(AT, U, BUR, 'Dispensations. Grace is a stamp.');
  z(AT, U, ECO, 'Sacred groves. A mill is a blasphemy with smoke.');
  z(AT, U, MER, 'Exams for clergy. The god-chair is not an exam.');
  z(AT, U, CHA, 'This voice is the faith. When it stops, they are drones in hats.');
  z(AT, U, PRAE, 'Temple guards. A night in the crypt can change the creed.');
  z(AT, U, LIB, 'They claim the soul, not the market — then tithe both.');
  z(AT, U, PART, 'Congregations vote feast days. Creed is not congregational.');
  z(AT, U, ISO, 'Unbelieving flags are a plague. Converted marches are pasture. Nothing else comes in.');
  z(AT, F, N, 'Diocese-nests under a Queen-god. Liturgy and labor are not separate shifts in either layer.');
  z(AT, F, POP, 'Revivals in the nests; the supreme office pretends they were always the creed.');
  z(AT, F, PAT, 'Alms in two queues. Hunger is a sermon federally and locally.');
  z(AT, F, BUR, 'Canon in two chanceries.');
  z(AT, F, CHA, 'This voice is the faith. Regional shepherds are listeners.');
  z(AT, F, PRAE, 'Temple guards federally and in the nest.');
  z(AT, F, CS, 'Limits on the wall in both palaces. Both interpret them as already fulfilled.');
  z(AT, F, THEO, 'The sacred office is the state in both palaces, then an influence chapel for the fiction of a civil code. Louder is the only change.');
  z(AT, C, N, 'Autocephalous holy nests share a supreme cleric they can ignore between councils. Real enough for festivals, not real enough to tax.');
  z(AT, C, CS, 'Each holy nest keeps canon it already fulfills. The supreme cleric’s earthly limits are a festival reading.');
  z(AT, C, THEO, 'Local prophet-offices already speak for the divine hive. Confederal extra holiness is a title they skip.');
  z(AT, Y, N, 'The prophet-office, plus a tolerated rite too expensive to crush.');
  z(AT, Y, CS, 'Limits on the wall, plus a footnote rite the wall does not mention.');
  z(AT, Y, TRAD, 'The Queen-god, plus a leftover brood-rite fenced by treaty.');
  z(AT, I, N, 'The Queen is worshipped at home; outer species meet her as a mission with a levy.');
  z(AT, I, POP, 'Core ecstasy; outer conversion. The hymn is exported.');
  z(AT, I, MIL, 'Sacred war office at home; assessment after the hymn abroad.');
  z(AT, I, PAT, 'Alms for the flock; tithes from the converted.');
  z(AT, I, THEO, 'The flock at home, the converted abroad, and a mission office so occupation can be preached.');
  z(AT, I, ISO, 'Unbelieving flags are a plague. Converted marches are the flock’s outer pasture. The pasture does not go out.');

  // Swarm collapse — hive anarchy, including 8B-style contradictions where stacked
  z(SW, U, CS, 'Someone scored a constitution on a comb wall. Nothing sits the throne to enforce it. The paper is a sermon against itself, and that is the terror.');
  z(SW, U, POP, 'The swarm still moves as a crowd. There is no name to follow except hunger.');
  z(SW, U, MIL, 'Every fragment is a sting. There is no civilian file because there is no file.');
  z(SW, U, PAT, 'Care is whoever still secretes food. It is not a ministry; it is luck.');
  z(SW, U, TRAD, 'Habit is the only Queen. Custom without a throne is traffic.');
  z(SW, U, THEO, 'They still sing to a missing god. The hymn does not steer.');
  z(SW, U, TECH, 'A few literate drones keep “plans.” The plans die when they do.');
  z(SW, U, REV, 'The collapse is still on the agenda. “After the Queen” is how they justify a committee that was supposed to dissolve.');
  z(SW, U, CORP, 'Whoever holds a comb invoices. There is no court, only coverage.');
  z(SW, U, BUR, 'Clipboards without a throne. The state they lost comes back as forms that nobody can stamp.');
  z(SW, U, ECO, 'The land is a stampede’s leftovers. A poisoned well is weather.');
  z(SW, U, MER, 'Skill is who can hold a checkpoint of bodies. Age and exam are jokes the swarm does not get.');
  z(SW, U, CHA, 'A name still rides at the front of a fragment. When that rider falls, the federation is a memory.');
  z(SW, U, PRAE, 'A militia that was supposed to dissolve now guards nothing. People call it defense while standing in a queue that has no clerk.');
  z(SW, U, LIB, 'No one can bind the swarm. Exit is just flying off. Some disasters go badly.');
  z(SW, U, PART, 'Attendance is collision. Meetings are traffic jams with opinions.');
  z(SW, U, ISO, 'Outside is where Queens still sit. This swarm prefers bad air and no flags.');
  z(SW, F, POP, 'Fragments federate by collision. Crowds stay local. There is no song, only traffic with letterhead.');
  z(SW, F, REV, 'Expropriation of a missing throne, in two addresses. “Just this once” is how a Queen comes back as clipboards.');
  z(SW, F, ECO, 'Local hunger and a federal river. Nothing sits to keep either.');
  z(SW, F, CHA, 'A name still on the radio. When it dies, federalism is the next collision.');
  z(SW, C, POP, 'Each fragment is a crowd. Confederal talk is humans trying to name a stampede.');
  z(SW, C, CHA, 'Each patch is a name. Confederal talk is how they divide hunger.');
  z(SW, C, ISO, 'The next valley is already abroad. A diet does not make it less so.');
  z(SW, Y, N, 'Most of the swarm collides equally. One fragment bargained a special truce with a leftover comb. Equals, except these equals.');
  z(SW, I, N, 'They will not say empire. They still take from the next valley for a common store that has no Queen, and leave a flag that is a stain.');
  z(SW, I, ISO, 'The swarm will not go to the world. The world is Queens. What they already overran is called home, and they will not discuss it as foreign.');
}

loadZytheraStacks();
